name: Pipeline de Integração Contínua

on:
  push:
    branches:
      - main # Define que esta pipeline é acionada automaticamente ao realizar push na branch "main"

jobs:
  build:
    runs-on: ubuntu-latest # Define que o trabalho será executado em um ambiente Ubuntu

    defaults:
      run:
        shell: bash -eux {0}

    steps:
      - name: Setup Node.js # Configuração do ambiente Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Utiliza a ação oficial para configurar a versão 16 do Node.js

      - name: Checkout do Código
        uses: actions/checkout@v2 # Utiliza a ação oficial para realizar o checkout do código

      - name: Instalar Dependências
        run: npm install --legacy-peer-deps # Executa o comando npm para instalar as dependências do projeto, incluindo dependências legadas

      - name: Analisar Qualidade do Código
        run: npm run lint # Executa o comando npm para realizar análise de qualidade estática do código

      - name: Build da Aplicação Vue.js
        run: npm run build # Executa o comando npm para compilar a aplicação Vue.js

      - name: Empacotar Artefatos # Empacotamento dos artefatos gerados
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
        # Utiliza a ação oficial para empacotar e fazer upload dos artefatos gerados na pasta "dist"

      - name: Notificar sobre o Build
        if: ${{ always() }}
        run: echo "O build foi concluído com sucesso!"
